### PR TITLE
Added drupal logo. Ticket 123

### PR DESCRIPTION
**Pull request by dsdeiz**
Screenshot:

### CODE REVIEW

**Comment by Luukyb** [comment]
Could you add an alt and title ? Also provide a screenshot of the result please.
In the ticket, it sounds like we need some spacing.

**Comment by Luukyb** [comment]
Could you add a screenshot ? Thanks

**Comment by dsdeiz** [comment]
[Screenshot](http://take.ms/gHs9r).

**Comment by Luukyb** [comment]
Please add it as a link. https://github.com/promet/drupalcampcebu2015/issues/123

**Comment by Luukyb** [comment]
Thanks @dsdeiz

**Pull request merged**
